//! The neural font: a small MLP that IS the font file.
//!
//! Input:  letter one-hot ⧺ joining-form one-hot ⧺ elongation scalar.
//! Output: GRID_W×GRID_H occupancy values ⧺ advance width (scaled).
//!
//! There are no glyph tables — every outline the engine draws is
//! generated by a forward pass through these weights.

use crate::shape::GlyphSource;
use crate::{Form, GlyphImage, GRID_H, GRID_W, MAX_ELONG};

pub const N_IN: usize = ALPHABET_LEN + 4 + 1;
/// The model predicts only the occupancy grid. The advance width is a
/// property of the generated shape: glyphs are right-aligned on the
/// canvas, so the pen simply moves to the leftmost generated column.
pub const N_OUT: usize = GRID_W * GRID_H;
pub const ALPHABET_LEN: usize = 57;

/// A dense layer: `out = act(W·x + b)`, weights row-major [n_out × n_in].
#[derive(Clone)]
pub struct Layer {
    pub n_in: usize,
    pub n_out: usize,
    pub w: Vec<f32>,
    pub b: Vec<f32>,
    pub relu: bool,
}

impl Layer {
    pub fn new(n_in: usize, n_out: usize, relu: bool, seed: &mut u64) -> Self {
        // He init with a tiny xorshift PRNG (deterministic builds).
        let scale = (2.0 / n_in as f32).sqrt();
        let mut rand = || {
            *seed ^= *seed << 13;
            *seed ^= *seed >> 7;
            *seed ^= *seed << 17;
            ((*seed >> 11) as f32 / (1u64 << 53) as f32 * 2.0 - 1.0) * scale
        };
        Layer {
            n_in,
            n_out,
            w: (0..n_in * n_out).map(|_| rand()).collect(),
            b: vec![0.0; n_out],
            relu,
        }
    }

    pub fn forward(&self, x: &[f32], out: &mut Vec<f32>) {
        out.clear();
        for o in 0..self.n_out {
            let row = &self.w[o * self.n_in..(o + 1) * self.n_in];
            let mut acc = self.b[o];
            for (wi, xi) in row.iter().zip(x) {
                acc += wi * xi;
            }
            out.push(if self.relu { acc.max(0.0) } else { acc });
        }
    }
}

#[derive(Clone)]
pub struct Mlp {
    pub layers: Vec<Layer>,
}

impl Mlp {
    /// The v0 architecture: N_IN → 128 → 128 → N_OUT (~52k params).
    pub fn new_font(seed: u64) -> Self {
        let mut s = seed.max(1);
        Mlp {
            layers: vec![
                Layer::new(N_IN, 128, true, &mut s),
                Layer::new(128, 128, true, &mut s),
                Layer::new(128, N_OUT, false, &mut s),
            ],
        }
    }

    pub fn n_params(&self) -> usize {
        self.layers.iter().map(|l| l.w.len() + l.b.len()).sum()
    }

    pub fn forward(&self, x: &[f32]) -> Vec<f32> {
        let mut a = x.to_vec();
        let mut next = Vec::new();
        for l in &self.layers {
            l.forward(&a, &mut next);
            std::mem::swap(&mut a, &mut next);
        }
        a
    }

    /// Forward pass keeping activations, then backprop MSE loss.
    /// Returns the sample loss; accumulates gradients into `grads`
    /// (same shapes as layers: (dW, db) per layer).
    pub fn backward(&self, x: &[f32], target: &[f32], grads: &mut [(Vec<f32>, Vec<f32>)]) -> f32 {
        // forward, keeping every activation
        let mut acts: Vec<Vec<f32>> = vec![x.to_vec()];
        for l in &self.layers {
            let mut out = Vec::new();
            l.forward(acts.last().unwrap(), &mut out);
            acts.push(out);
        }
        let y = acts.last().unwrap();
        let n = target.len() as f32;
        let mut delta: Vec<f32> = y.iter().zip(target).map(|(a, t)| 2.0 * (a - t) / n).collect();
        let loss: f32 = y.iter().zip(target).map(|(a, t)| (a - t) * (a - t)).sum::<f32>() / n;
        // backprop
        for (li, l) in self.layers.iter().enumerate().rev() {
            let a_in = &acts[li];
            let (dw, db) = &mut grads[li];
            for o in 0..l.n_out {
                let d = delta[o];
                db[o] += d;
                let row = &mut dw[o * l.n_in..(o + 1) * l.n_in];
                for (r, ai) in row.iter_mut().zip(a_in) {
                    *r += d * ai;
                }
            }
            if li > 0 {
                let mut prev = vec![0.0f32; l.n_in];
                for o in 0..l.n_out {
                    let d = delta[o];
                    let row = &l.w[o * l.n_in..(o + 1) * l.n_in];
                    for (p, wi) in prev.iter_mut().zip(row) {
                        *p += d * wi;
                    }
                }
                // through the previous layer's ReLU
                for (p, a) in prev.iter_mut().zip(&acts[li]) {
                    if *a <= 0.0 {
                        *p = 0.0;
                    }
                }
                delta = prev;
            }
        }
        loss
    }
}

/// Encode a model input vector.
pub fn encode_input(letter_idx: usize, form: Form, elong: f64) -> Vec<f32> {
    let mut x = vec![0.0f32; N_IN];
    x[letter_idx] = 1.0;
    x[ALPHABET_LEN + form.index()] = 1.0;
    x[ALPHABET_LEN + 4] = (elong / MAX_ELONG as f64) as f32;
    x
}

/// Decode a model output vector into a glyph image. The advance is
/// derived from the grid: distance from the canvas's right edge to the
/// leftmost occupied column.
pub fn decode_output(y: &[f32]) -> GlyphImage {
    let mut img = GlyphImage::empty();
    for (i, v) in y[..GRID_W * GRID_H].iter().enumerate() {
        img.cells[i] = *v > 0.5;
    }
    let leftmost = (0..GRID_W).find(|&x| (0..GRID_H).any(|y| img.get(x, y)));
    img.advance = match leftmost {
        Some(x) => (GRID_W - x) as f64,
        None => 1.0,
    };
    img
}

/// Encode a teacher glyph image as a training target.
pub fn encode_target(img: &GlyphImage) -> Vec<f32> {
    img.cells.iter().map(|&c| if c { 1.0 } else { 0.0 }).collect()
}

/// The neural font as a glyph source: one forward pass per glyph.
pub struct NeuralFont {
    pub mlp: Mlp,
    pub alphabet: Vec<char>,
}

impl GlyphSource for NeuralFont {
    fn glyph(&self, c: char, form: Form, elong: f64) -> Option<GlyphImage> {
        let c = crate::art::canonical_char(c);
        let idx = self.alphabet.iter().position(|&a| a == c)?;
        let y = self.mlp.forward(&encode_input(idx, form, elong));
        Some(decode_output(&y))
    }
}
